### ISSUE TITLE
Asset FileSystem

### ISSUE THREAD

**Issue by Mempler** [Mempler/IceSDK#30]
Our current way of storing each asset is a simple inefficient Key:Ptr database, actually. we don't even store the pointer, just the size of that file which will be calculated on the fly. This is highly inefficient and requires an overhaul.

### TODO:
* [ ] Recreate the File System with proper management
* [ ] Multi dimensional File System (fs inside fs)
* [ ] a Proper way to Write / Read into that File System
* [ ] Specially crafted file types for
  * [ ] Textures
  * [ ] Audio
  * [ ] Text
  * [ ] Font
  * [ ] Video / Animated Texture
  * [ ] Raw Binary
  * [ ] Language Files
